# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - app-atxknc5vuyzgy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
    contents: read #This is required for actions/checkout
    security-events: write # Required to upload SARIF results (Bandit)

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # CI tooling
          pip install ruff mypy bandit
      
      - name: Lint (Ruff)
        run: |
          # Fail on critical issues only to start: syntax errors (E9) and undefined names (F)
          ruff check . --output-format=github --select E9,F
      
      - name: Type check (Mypy)
        run: |
          # Limit scope to project modules; ignore missing third-party types to reduce noise
          mypy app main.py --ignore-missing-imports --install-types --non-interactive
      
      - name: Security scan (Bandit) and upload SARIF
        run: |
          bandit -r . -x venv,tests,__pycache__ \
            -f sarif -o bandit.sarif \
            -lll -iii
        
      - name: Upload Bandit SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A49EA0B5134849BFA033ED92B8CD0BDE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0A098C76DF834817980648D5A643BA33 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_56A0C2AC03D34BECA1D9E01ACBECC670 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'app-atxknc5vuyzgy'
          slot-name: 'Production'
          